platform :ios, '5.1'
pod 'RestKit', '~>  0.20.0'
pod 'Facebook-iOS-SDK'
pod 'SVProgressHUD'
pod 'ECSlidingViewController'
pod 'Reachability'
pod 'AQGridView'
pod 'CAAnimationBlocks'
pod 'SKBounceAnimation'
pod 'OHAttributedLabel'
pod 'EGOCache', '~> 2.0'
pod 'AWSiOSSDK'
